/* eslint-disable @typescript-eslint/naming-convention */

export const SOCKET_EVENT_NAMES = {
	CLIENT: {
		JOIN_ROOM      : 'CLIENT:JOIN_ROOM',
		SEND_USERID    : 'CLIENT:SEND_USERID',
		SEND_MESSENGER : 'CLIENT:SEND_MESSENGER',
		CREATE_ROOM    : 'CLIENT:CREATE_ROOM',
	},
	SERVER_SOCKET: {
		SEND_DATA_FOR_CHAT_ROOM_DESCRIPTION:
			'SERVER_SOCKET:SEND_DATA_FOR_CHAT_ROOM_DESCRIPTION',
		SEND_DATA_FOR_CHAT_ROOM_MESSENGERS:
			'SERVER_SOCKET:SEND_DATA_FOR_CHAT_ROOM_MESSENGERS',
	},
};

export enum ENUM_MESSAGE_TYPE {
    INFO = 'INFO',
    TEXT = 'TEXT',
    IMAGE = 'IMAGE',
}

export enum ENUM_MESSAGE_INFO_TYPE {
    JOIN_CHAT = 'JOIN_CHAT',
    LEAVE_CHAT = 'LEAVE_CHAT',
    INVITED = 'INVITED',
    REJECTED = 'REJECTED',
    CHANGE_NAME_GROUP = 'CHANGE_NAME_GROUP',
}
