export enum ENUM_ENVIRONMENT_VARIABLE {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    MONGODB_URL_CONNECT = 'MONGODB_URL_CONNECT',
    SECRET_OR_PUBLIC_KEY = 'SECRET_OR_PUBLIC_KEY',
    NODEMAILER_MAIL_USERNAME = 'NODEMAILER_MAIL_USERNAME',
    NODEMAILER_MAIL_PASSWORD = 'NODEMAILER_MAIL_PASSWORD',
    NODEMAILER_MAIL_SERVICE = 'NODEMAILER_MAIL_SERVICE',
    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    COOKIE_SECRET_KEY = 'COOKIE_SECRET_KEY',
    SECURE_SESSION_SECRET_KEY = 'SECURE_SESSION_SECRET_KEY',
    SECURE_SESSION_SALT = 'SECURE_SESSION_SALT',
    AWS_REGION = 'AWS_REGION',
    AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
    AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
    AWS_PUBLIC_BUCKET_NAME = 'AWS_PUBLIC_BUCKET_NAME',
}
export const getEnv = (env: string): any => {
    if (env === ENUM_ENVIRONMENT_VARIABLE.SECRET_OR_PUBLIC_KEY) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.SECRET_OR_PUBLIC_KEY] || 'HEHE';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.NODE_ENV) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.NODE_ENV] || 'HEHE';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.PORT) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.PORT] || 3000;
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.MONGODB_URL_CONNECT) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.MONGODB_URL_CONNECT] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.NODEMAILER_MAIL_USERNAME) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.NODEMAILER_MAIL_USERNAME] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.NODEMAILER_MAIL_PASSWORD) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.NODEMAILER_MAIL_PASSWORD] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.NODEMAILER_MAIL_SERVICE) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.NODEMAILER_MAIL_SERVICE] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.REDIS_HOST) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.REDIS_HOST] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.REDIS_PORT) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.REDIS_PORT] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.COOKIE_SECRET_KEY) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.COOKIE_SECRET_KEY] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.SECURE_SESSION_SECRET_KEY) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.SECURE_SESSION_SECRET_KEY] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.SECURE_SESSION_SALT) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.SECURE_SESSION_SALT] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.AWS_REGION) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.AWS_REGION] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.AWS_ACCESS_KEY_ID) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.AWS_ACCESS_KEY_ID] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.AWS_SECRET_ACCESS_KEY) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.AWS_SECRET_ACCESS_KEY] || '';
    }
    if (env === ENUM_ENVIRONMENT_VARIABLE.AWS_PUBLIC_BUCKET_NAME) {
        return process.env[ENUM_ENVIRONMENT_VARIABLE.AWS_PUBLIC_BUCKET_NAME] || '';
    }

    return '';
};
